*;
*  TO DO: Run the code.  Then select Run > Recall Last Submit
*         to recall the code generated by PROC IMPORT.
*;

options validvarname=any;

proc import out=work.calcium
  file="&PATH\Calcium.csv"
  dbms=csv
  replace;
  guessingrows=max;
run; quit;