
****Failure should be missing. It should not be zero in the level*****************************;;;
%macro exact (ds=_last_,bygrp=,var=,class=,out=1,Pdec=1,Dec=1,keep=N,CI=95);
Options NOQUOTELENMAX ;
*Binomail Variable - var to make it 1 (response) vs missing (non-respose);
data tab;
set &ds;
if &var ne 1 then call missing(&var);*To use Proc Means for n;
Run;
%if (&bygrp NE %str( )) %then %do;
proc sort data=tab out=tab;
by &bygrp;
run;
%END;
*Get Freq for calculation;
ods listing close;
Proc Means data=tab noprint;
%if (&bygrp NE %str( )) %then %do;
by &bygrp;%END;
%if (&CLASS NE %str( )) %then %do;
class &class;;%END;;
var &var;
output out=stat1 n=x ;
run;

ods listing;
Data stat2;
length var $40. param $40.;
set stat1;
%if (&bygrp NE %str( )) %then %do;   by &bygrp;        %end;
%if (&CLASS NE %str( )) %then %do;
var=vvalue(&class);
if missing(var) then var='TOTAL';
param=vname(&class);%END;
%ELSE %DO;
PARAM='' ; VAR='' ;
%END;
n=_freq_;
keep &bygrp var param x n ;
run;
%*let CI=95;
Data _null;
alpha_u=(100- &CI. )/200;
alpha_l=1-alpha_u;
Call Symputx ("alpha_u" , alpha_u);
Call Symputx ("alpha_l" , alpha_l);
Run;
/*Calulate Exacts 95%CI;*/
data ci_&out;
 set STAT2;
if x=0 and n=0 then do;
	CI_LOW=0;
	CI_HIGH=1;
	Put "There is N=0 and X=0 in data." ;
	End;
else if n ne 0 then do;
	p=x/n;
	PERCENT=P*100;
	if p=0 then CI_LOW=0;
	if p=1 then CI_HIGH=1;
	if p ne 0 then CI_LOW=(1-betainv(&alpha_l,(n-x+1),x));
	if p ne 1 then CI_HIGH=(1-betainv(&alpha_u,(n-x),x+1));
end;
prop=compbl(PUT(x,6.)||'/'||put(n,8.)||' ('||Put(PERCENT,6.&Pdec.)||')');
CI_95=compbl( '('||put(CI_LOW*100,5.&dec.)||', '||put(CI_HIGH*100,5.&dec.)||')');
	format PERCENT CI_LOW CI_HIGH p 5.&dec. ;
%if  (&KEEP ne Y ) %then %do;
Drop n x CI_LOW CI_HIGH PERCENT p;
%end;
run;

%Mend ;

